apiVersion: 1
datasources:
  - name: TradingBot-PostgreSQL
    type: postgres
    url: postgres:5432
    database: trading_bot
    user: grafana_reader
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
